In [1]:
# List vs NumPy

In [4]:
a1 = [1,2,3,4,5,6,7,8,9,10]
print(a1)

# Square of each element of list
a1*a1


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
# Using for loop
a1 = [1,2,3,4,5,6,7,8,9,10]
for i in a1 :
    print(i*i)

1
4
9
16
25
36
49
64
81
100


In [8]:
# using list comprehension

a2 = [i*i for i in a1]
print(a2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [ ]:
######################

In [12]:
import numpy as np

# converting the list into array
print(a1)
print(type(a1))


arr1 = np.array(a1)
print(arr1)
print(type(arr1))#<class 'numpy.ndarray'> Numpy n- dimensional Array


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [13]:
5 ** 2

25

In [14]:
5**3

125

In [15]:
arr1 = np.array(a1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
arr1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [19]:
print(arr1**2)
print(arr1**3)
print(arr1**4)

[  1   4   9  16  25  36  49  64  81 100]
[   1    8   27   64  125  216  343  512  729 1000]
[    1    16    81   256   625  1296  2401  4096  6561 10000]


In [20]:
# 1. can perform elementwise operations
# 2. faster than list operations

In [24]:
# Faster than list 

# Using list
a11 = list(range(100000))
%timeit [i*i for i in a11] 

# using numpy
arr2  = np.array(a11)
%timeit [arr2**2]

7.87 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
120 µs ± 5.08 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
# why faster ? it is  written C language