In [2]:
# Topic Covered 
# Array Atributes and Array Creation

In [3]:
import numpy as np

In [7]:
listA = [1,2,3,4,5,6,7,8,9,10]
listA
print(type(listA))#<class 'list'>

<class 'list'>


In [6]:

arr1 = np.array(listA)
arr1
print(type(arr1))#<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [ ]:
# array supports elementwise operation

In [ ]:
# My Q is What is defference between list and Array?
# Ans:Here's a table summarizing the key differences between lists and arrays in Python:

# | Feature              | List                                | Array (NumPy)                             |
# |----------------------|-------------------------------------|-------------------------------------------|
# | Data Type            | Can store mixed data types         | Typically stores homogeneous data types  |
# | Size                 | Dynamic, can grow or shrink        | Static, fixed size                       |
# | Performance          | Slower for numerical operations    | Faster for numerical operations           |
# | Indexing             | Zero-based indexing                 | Zero-based indexing                       |
# | Functions            | Limited built-in functions          | Extensive functions for array operations |
# | Libraries            | Part of Python's standard library   | Requires NumPy library                    |
# | Multidimensional     | Limited support for n-dimensional   | Full support for n-dimensional arrays     |
# | Element-wise        | Requires iteration for operations  | Supports vectorized operations             |



In [11]:
# 1-Dimensional Array(one dimensionAL Array)

    # attributes of arr2
    
arr1 = np.array(listA)
arr1    
    
#ndim    
print(arr1.ndim) # 1 (Determini one dimensional array)

# shape
print(arr1.shape)#(10,)  # (x_axis,y_axis) (0th,1st) (rows,coln)

# size

print(arr1.size) #10 -> Total number of element inside Array.




1
(10,)
10


In [13]:
arr2 = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G'])
arr2

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U1')

In [16]:
# Attribute of arr2
# ndim

print(arr2.ndim)#1

# shape
print(arr2.shape)#(7,)

#size
print(arr2.size)#7





1
(7,)
7


In [21]:
# 1-D Array Creation 
#    1. by passing a list 
#    2. using arange() method
#    3. using linspace() method





list(range(10))



[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
list(range(1,10))# last element of not included


[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [25]:
list(range(1,10,0.5)) # This is the limitation of the list, we can use numpy methods.

TypeError: 'float' object cannot be interpreted as an integer

In [26]:
arr3= np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr3 = np.arange(1,10)
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

In [30]:
arr3 = np.arange(1,10,0.5)
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [31]:
# Attribute of array

#ndim
print(arr3.ndim)#1
#shape
print(arr3.shape)#(18,)
#size
print(arr3.size)#18


1
(18,)
18


In [34]:
# Using linspace


arr4 = np.linspace(1,10) #the element is included
arr4

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [35]:
# Attribute of array

#ndim
print(arr4.ndim)#1
#shape
print(arr4.shape)#(50,)
#size
print(arr4.size)#50


1
(50,)
50


In [36]:
arr4 = np.linspace(1,10,18) #the element is included
arr4

array([ 1.        ,  1.52941176,  2.05882353,  2.58823529,  3.11764706,
        3.64705882,  4.17647059,  4.70588235,  5.23529412,  5.76470588,
        6.29411765,  6.82352941,  7.35294118,  7.88235294,  8.41176471,
        8.94117647,  9.47058824, 10.        ])