In [1]:
import numpy as np

In [3]:
a = [1,2,3,4,5,6]
print(a)

[1, 2, 3, 4, 5, 6]


In [5]:
arr1 = np.array(a)
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
############### 2-D Array Creation ###################

In [6]:
b = [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]
print(b)

[[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]]


In [7]:
arr2 = np.array(b)
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [8]:
# ndim
arr2.ndim # 2

2

In [9]:
# shape
arr2.shape #(2,8) => 2-row & 8-column

(2, 8)

In [10]:
#size

arr2.size# 16 {Total Number of elements}

16

In [11]:
# using aranage() and reshape()

In [12]:
arr3  = np.arange(12)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)
12


In [13]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
# reshaping the array
arr4 = np.reshape(2,6)
arr4

ValueError: cannot reshape array of size 1 into shape (6,)

In [15]:
arr3.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [16]:
arr3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr3.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [18]:
arr3.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
arr3.reshape(1,12) # #column vector

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [20]:
arr3.reshape(12,1) #raw vector

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [21]:
arr3.dtype

dtype('int32')

In [24]:
arr4 = np.linspace(1,10,15)
arr4.reshape(5,3)

array([[ 1.        ,  1.64285714,  2.28571429],
       [ 2.92857143,  3.57142857,  4.21428571],
       [ 4.85714286,  5.5       ,  6.14285714],
       [ 6.78571429,  7.42857143,  8.07142857],
       [ 8.71428571,  9.35714286, 10.        ]])

In [26]:
# reshaping the array in single command
arr4 = np.linspace(1,10,15).reshape(3,5)
arr4

array([[ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857],
       [ 4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429],
       [ 7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ]])

In [27]:
arr4.dtype

dtype('float64')

c  = [1,2,3,4,'a','b','c','d']
arr5 = np.array(c)
print(arr5)


In [28]:
c = [1,2,3,4,'a','b','c','d']
arr5= np.array(c)
print(arr5)


['1' '2' '3' '4' 'a' 'b' 'c' 'd']


In [29]:
arr5.dtype

dtype('<U11')

In [30]:
arr5

array(['1', '2', '3', '4', 'a', 'b', 'c', 'd'], dtype='<U11')

In [31]:
arr5.shape

(8,)

In [32]:
# If one dimension is unknown

In [33]:
arr3.reshape(6,-1) # shape  =  12 , rows = 6 ,coln  = ? : if one of the values is dummy , it will be calculated and replaced by numpy


array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [34]:
arr3.reshape(-6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [35]:
arr3.reshape(-6,-2)

ValueError: can only specify one unknown dimension