In [ ]:
# Rivision 

In [1]:
import numpy as np

In [2]:
# 2-D Array Creation 
# using arange() and reshape()

In [3]:
d = [[1,2,3,4],['a','b','c','d']]
arr1=np.array(d)
print(arr1)

[['1' '2' '3' '4']
 ['a' 'b' 'c' 'd']]


In [10]:
print(list(range(10)))

print(list(range(1,10,2)))

np.arange(10)
arr2 = np.arange(1,10,0.5)
arr2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]


array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
# ndim
arr2.ndim

1

In [12]:
# shape
arr2.shape

(18,)

In [13]:
# size
arr2.size

18

In [14]:
arr2.dtype

dtype('float64')

In [15]:
# reshape 

arr2.reshape(2,9) # (row,column)

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [19]:
# reshape

arr2.reshape(9,2)

array([[1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [20]:
# row vector
arr2.reshape(1,18)

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
        7.5, 8. , 8.5, 9. , 9.5]])

In [21]:
# column vector
arr2.reshape(18,1)

array([[1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5],
       [5. ],
       [5.5],
       [6. ],
       [6.5],
       [7. ],
       [7.5],
       [8. ],
       [8.5],
       [9. ],
       [9.5]])

In [22]:
arr2.reshape(9,-2) # One value is known ,prediction detected.

array([[1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [24]:
arr2.reshape(-9,-2) # Two value is unknown ,prediction failed.

ValueError: can only specify one unknown dimension

In [25]:
################ Initial PLacaholders ######################

In [ ]:
# 1.zeros()
# 2.ones()
# 3.eye()
# 4.diag()


In [27]:
# zeros() 

np.zeros(3,3)

TypeError: Cannot interpret '3' as a data type

In [28]:
# zeros() 

np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [33]:
# ones

np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
# identiity matrix : Diadonally printed one in whole matrix.

# eye()
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [39]:
# diag : diagonally printed this numbers

np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [40]:
np.diag([10,20,30,40,50])

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 40,  0],
       [ 0,  0,  0,  0, 50]])

In [ ]:
# How to solve this Matrix
# 1.solve deteminant
# 2.solve inverse
# 3.Matrix Operation

In [63]:
#1. Solve determinant

aa = [[1,2,3],
      [4,5,6],
      [7,8,9]]
print(aa)
print(type(aa))



matrix = np.array(aa)


determinant = np.linalg.det(matrix)
print("Determinant:", determinant) # Determinant: -9.51619735392994e-16


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
Determinant: -9.51619735392994e-16


In [64]:
# 2.solve inverse

aa = [[1,2,3],
      [4,5,6],
      [7,8,9]]
print(aa)
print(type(aa))



matrix = np.array(aa)

# Check if the determinant is non-zero
determinant = np.linalg.det(matrix)

if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix)
    print("Inverse Matrix:")
    print(inverse_matrix)
else:
    print("Matrix is singular; it does not have an inverse.")

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
Inverse Matrix:
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [ ]:
###########    indexing and Slicing   ############

In [73]:
# 3.Matrix Operation
aa1 = [[1,2,3],
      [4,5,6],
      [7,8,9]]
print(aa1)

aa2 = [[1,2,3],
      [4,5,6],
      [7,8,9]]
print(aa2)

result_matrix = aa1 + aa2
print("Result Matrix (Addition):")
print(result_matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Result Matrix (Addition):
[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [42]:
# with 1-D Array

arr3 = np.arange(3,11)
arr3

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
# Indexing

arr3[2]

5

In [44]:
arr3[5]

8

In [45]:
arr3[7]

10

In [46]:
arr3[-1] # 10 , neg indexing also works here

10

In [49]:
# slicing in 1d 
# array[start:end] #last value is not included
arr3 = np.arange(3,11)
arr3
# arr3[1:3]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr3[1:3] #[4,5]

array([4, 5])

In [51]:
arr3[2:5]

array([5, 6, 7])

In [52]:
# it will take default start and end values , if lef blank !!

In [55]:
arr3[:5]

array([3, 4, 5, 6, 7])

In [56]:
arr3[2:]

array([ 5,  6,  7,  8,  9, 10])