In [1]:
# Rivision 

# 2-D Array 


import numpy as np




In [2]:
arr1 = np.arange(5,15)

In [3]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr1[4] 

9

In [5]:
arr1[1:5] # #last value is not included

array([6, 7, 8, 9])

In [6]:
arr1[:-7]

array([5, 6, 7])

In [7]:
arr1[-1:-7]

array([], dtype=int32)

In [8]:
arr1[0:8:2]

array([ 5,  7,  9, 11])

In [9]:
arr1[0:11:-1]

array([], dtype=int32)

In [10]:
arr1[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5])

In [ ]:
# 2-D Array

In [11]:
arr2 = np.arange(15).reshape(5,3)
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [12]:
arr2[0]

array([0, 1, 2])

In [13]:
arr2[3]

array([ 9, 10, 11])

In [14]:
arr2[4]

array([12, 13, 14])

In [15]:
arr2[0:3] # last element is not included.

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# arr2[rows,col]
# arr2[strat_rows:end_rows,start_col:end_col]

In [18]:
arr2[0:2,0:2] #arr2[rows,column]

array([[0, 1],
       [3, 4]])

In [19]:
arr2[0:2,1:3]

array([[1, 2],
       [4, 5]])

In [20]:
arr2[2:4,1:3]

array([[ 7,  8],
       [10, 11]])

In [21]:
arr2[0:4,1:4]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [22]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [23]:
arr2[3:5,0:2]

array([[ 9, 10],
       [12, 13]])

In [24]:
arr2[1:3,1:]

array([[4, 5],
       [7, 8]])

In [58]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [59]:
arr2[0:4:2,0:3] #Jump value in 2-D array.

array([[0, 1, 2],
       [6, 7, 8]])

In [60]:
arr2[0:4:2,0:3:2]

array([[0, 2],
       [6, 8]])

In [61]:
arr2[1:4:,1:3:] # default value is '0' indexing / last value is not included.

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
######### Indexing with Boolean value arrays   #######

In [ ]:
# Indexing with Boolean value arrays
# fancy masking : also known as boolean masking.
# boolean Masking

In [25]:
arr3 = np.arange(13)

In [26]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
arr3[7]

7

In [29]:
print(10>4)

True


In [30]:
print(10<3)

False


In [31]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
arr3 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True])

In [33]:
print(arr3 > 10)

[False False False False False False False False False False False  True
  True]


In [34]:
print(arr3 <= 7)

[ True  True  True  True  True  True  True  True False False False False
 False]


In [35]:
arr3 % 3 == 0 

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False,  True])

In [36]:
arr3 % 2 == 0 

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True])

In [37]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
arr3%2==0 and arr3%3 == 0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
(arr3%2==0) & (arr3%3 == 0)

array([ True, False, False, False, False, False,  True, False, False,
       False, False, False,  True])

In [43]:
arr4 = np.arange(15).reshape(5,3)
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [44]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [45]:
arr4[(arr4%3==0)|(arr4%2==0)]  # outPut will be 1-D Array.

array([ 0,  2,  3,  4,  6,  8,  9, 10, 12, 14])

In [46]:
arr4

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [51]:
arr5 = arr4[(arr4%5 == 0)]
arr5              # outPut will be 1-D Array.

array([ 0,  5, 10])

In [54]:
arr6 = arr4[(arr4%10 == 0)] #outPut will be 1-D Array.
arr6

array([ 0, 10])

In [55]:
arr7 = np.arange(12).reshape(3,4)
arr7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [57]:
arr7[(arr7%2==0)]

array([ 0,  2,  4,  6,  8, 10])