In [2]:
# Slicing the 2-D array.

import numpy as np

In [3]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
arr2 = np.arange(25).reshape(5,5)

In [6]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [7]:
arr2[0,0]

0

In [8]:
arr2[0:4,0:4] # last element is not consider.

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [9]:
arr2[-1] # getting row

array([20, 21, 22, 23, 24])

In [10]:
arr2[-1,-1]

24

In [11]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
arr2[-2,-2]

18

In [13]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr2[0:5,0]

array([ 0,  5, 10, 15, 20])

In [16]:
# Negative Indexing

arr2[-1]

array([20, 21, 22, 23, 24])

In [17]:
arr2[-2]

array([15, 16, 17, 18, 19])

In [18]:
arr2[-5]

array([0, 1, 2, 3, 4])

In [19]:
arr2[0,-1]

4

In [20]:


arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr2[4,4]

24

In [22]:
arr2[-1,-1]

24

In [23]:
# Jump Value

arr2[0:5:2,0:5:2] #last one is not included.

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [24]:
arr2[1:4,2:4]

array([[ 7,  8],
       [12, 13],
       [17, 18]])

In [25]:
arr2[0:5:-1,0:5:-1]

array([], shape=(0, 0), dtype=int32)

In [26]:
#Indexing with Boolean arrays

In [27]:
arr3 = np.arange(5,25)

In [28]:
arr3

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [31]:
np.size(arr3) # Standerd Formate for the write.

20

In [32]:
arr3.size

20

In [33]:
arr4 = np.arange(5,25).reshape(5,4)

In [34]:
arr4

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [35]:
Mask1 = arr4 % 2 == 0 

In [36]:
Mask2 = arr4 % 5 == 0

In [37]:
arr4[Mask1 | Mask2] # outPut will be 1-D Array.

array([ 5,  6,  8, 10, 12, 14, 15, 16, 18, 20, 22, 24])

In [ ]:
# /HW
1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


1. 'Priya', 'Rohit', 'Aryan'
2. 'Riya','Devanshi'
3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
4. 'Avni'
5. 'Neha'

2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35

In [39]:
# 1.Q> slice the array to get below name.
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


In [40]:
# OutPuts:-
# 1. 'Priya', 'Rohit', 'Aryan'
s[0]

array(['Priya', 'Rohit', 'Aryan'], dtype='<U8')

In [41]:
# 2.
s[2,1:3]

array(['Riya', 'Devanshi'], dtype='<U8')

In [42]:
# 3.
s[1:3,0:3]

array([['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']], dtype='<U8')

In [43]:
#4.
s[1,1]

'Avni'

In [45]:
# 5.
s[1,0]

'Neha'

In [46]:
#####  2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
score
# 1. find all scores > 50
# 2. find all scores <35

array([[93, 58, 33],
       [55, 84, 27],
       [93, 15, 10],
       [75, 61, 95],
       [36, 67, 53]])

In [47]:
# 1. find all scores > 50

score[score > 50]

array([93, 58, 55, 84, 93, 75, 61, 95, 67, 53])

In [48]:
score.size

15

In [49]:
# 2. find all scores <35

score[score > 35]

# HomeWork Complited

array([93, 58, 55, 84, 93, 75, 61, 95, 36, 67, 53])

In [50]:
#########  Universal Function #############

In [52]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [53]:
print(a)
print(b)

[11 22 33 44 55]
[1 2 3 4 5]


In [54]:
# Addition

print(a + b)

# Sub

print(a - b)

# Mul

print(a * b)

# Div

print(a/b)

[12 24 36 48 60]
[10 20 30 40 50]
[ 11  44  99 176 275]
[11. 11. 11. 11. 11.]


In [56]:
# Program


# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Basic arithmetic operations with ufuncs
addition_result = np.add(array1, array2)
subtraction_result = np.subtract(array1, array2)
multiplication_result = np.multiply(array1, array2)
division_result = np.divide(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Addition Result:", addition_result)
print("Subtraction Result:", subtraction_result)
print("Multiplication Result:", multiplication_result)
print("Division Result:", division_result)

# Other ufuncs
square_root_result = np.sqrt(array1)
exponential_result = np.exp(array1)
sine_result = np.sin(array1)

print("Square Root Result:", square_root_result)
print("Exponential Result:", exponential_result)
print("Sine Result:", sine_result)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Addition Result: [ 7  9 11 13 15]
Subtraction Result: [-5 -5 -5 -5 -5]
Multiplication Result: [ 6 14 24 36 50]
Division Result: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Square Root Result: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential Result: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine Result: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
