In [1]:
import numpy as np

In [2]:
x1 = np.array([10,20,30]) #list  =  1D Array 
y1 = np.array([[1],[2],[3],[4]]) #list of list = 2D array

In [3]:
x1

array([10, 20, 30])

In [4]:
y1

array([[1],
       [2],
       [3],
       [4]])

In [5]:
# ndim
print(x1.ndim)#1-D
print(y1.ndim)#2-D


1
2


In [6]:
# size
print(x1.size)#3
print(y1.size)#4

3
4


In [7]:
# shape

print(x1.shape)#(3,)  This means that x1 is a 1D array with a length of 3.
                #      It has 3 elements in a single row, so it's a row vector.
    
    
print(y1.shape)#(4,1) =>(rows,colm)

(3,)
(4, 1)


In [8]:
x1

array([10, 20, 30])

In [9]:
y1

array([[1],
       [2],
       [3],
       [4]])

In [10]:
# UniverSal Operation
print(x1 + y1) #Addtion

[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


In [11]:
print(x1 * y1) # Multiplication.

[[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]


In [12]:
print(x1 + 1)

[11 21 31]


In [13]:
print(x1 * 2)

[20 40 60]


In [15]:
x2 = np.array([10,20,30,40]) #list  =  1D Array 
y2 = np.array([[1],[2],[3],[4]]) #list of list = 2D array

In [16]:
print(x2)
print(y2)

[10 20 30 40]
[[1]
 [2]
 [3]
 [4]]


In [17]:
x2 + y2    #(4*4) + (4*4)

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [18]:
arr1 = np.arange(12).reshape(3,4)

In [19]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
arr1 + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [21]:
arr1 + 1.5

array([[ 1.5,  2.5,  3.5,  4.5],
       [ 5.5,  6.5,  7.5,  8.5],
       [ 9.5, 10.5, 11.5, 12.5]])

In [22]:
arr1  + 1.75

array([[ 1.75,  2.75,  3.75,  4.75],
       [ 5.75,  6.75,  7.75,  8.75],
       [ 9.75, 10.75, 11.75, 12.75]])

In [23]:
# splitting 

In [25]:
gg = np.arange(9)
print(gg)

[0 1 2 3 4 5 6 7 8]


In [28]:
# splitting
arr2 = np.split(gg,3) #the o/p will be a list of arrays
arr2

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [29]:
print(arr2[0])
print(arr2[1])
print(arr2[2])

[0 1 2]
[3 4 5]
[6 7 8]


In [31]:
np.split(gg,3)[0]


array([0, 1, 2])

In [38]:
 zz = np.arange(16).reshape(4,4)
print(zz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [39]:
np.split(zz,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [40]:
#0-row distribution
#1-colm-distribution

np.split(zz,4,axis=0) #row distribution

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [41]:
np.split(zz,4,axis=1) # colmn distribution

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [45]:
# Example:-

aa = np.arange(20).reshape(5,4)
print(aa)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [51]:
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [59]:
print(np.split(aa,5,axis=0))
print(np.split(aa,4,axis=1))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19]])]
