In [1]:
import numpy as np

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.split(a,3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [5]:
np.split(a,7) # should be Equal dividation.#equal division can be done only , else error

ValueError: array split does not result in an equal division

In [6]:
b = np.arange(16).reshape(4,4)

In [7]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
b.ndim

2

In [9]:
np.split(b,4) # default axis is 0.

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [10]:
np.split(b,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [11]:
np.split(b,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [14]:
cc = np.arange(9).reshape(3,3)


In [15]:
cc

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.split(cc,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [18]:
np.split(cc,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [ ]:
# hsplit

In [19]:
np.hsplit(cc,3) #  hsplit perForm =>vertical split

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [20]:
# vsplit
np.vsplit(cc,3) #vsplit perform => Horizontal split.

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [26]:
##### Aggregate Function  ######

In [27]:
t1 = np.array([11,12,13,14])
t2 = np.array([1,2,3,4])

In [28]:
t1

array([11, 12, 13, 14])

In [29]:
t2

array([1, 2, 3, 4])

In [30]:
# U_function

t1 + t2

array([12, 14, 16, 18])

In [31]:
t1 - t2

array([10, 10, 10, 10])

In [32]:
t1 / t2

array([11.        ,  6.        ,  4.33333333,  3.5       ])

In [33]:
t1 * t2

array([11, 24, 39, 56])

In [34]:
t1 = np.array([11,12,13,14,0])
t2 = np.array([1,2,3,4,5])

In [35]:
t2 / t1 # Divided by zero is Supported in Numpy.

C:\Users\hp\AppData\Local\Temp\ipykernel_5724\490856821.py:1: RuntimeWarning: divide by zero encountered in divide
  t2 / t1


array([0.09090909, 0.16666667, 0.23076923, 0.28571429,        inf])

In [43]:
# In 1-D ,Array.
s1 = np.array([11,12,13,14,45])
s2 = np.array([1,2,3,4,5])

In [37]:
s1

array([11, 12, 13, 14,  0])

In [38]:
s2

array([1, 2, 3, 4, 5])

In [39]:
# sum:All element added in this array.
# In s1, All the element is added.

np.sum(s1)

50

In [40]:
# mean
np.mean(s2)

3.0

In [41]:
# max
print(np.max(s1))
print(np.max(s2))

14
5


In [44]:
# min

print(np.min(s1))
print(np.min(s2))

11
1


In [45]:
# In 2-D Array.

In [46]:
qq = np.arange(16).reshape(4,4)

In [47]:
qq

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.sum(qq) # All element is added.

120

In [51]:
np.sum(qq,axis=0) # columnwise element is added.

array([24, 28, 32, 36])

In [52]:
np.sum(qq,axis=1) # Row-wise element is added.

array([ 6, 22, 38, 54])

In [57]:
# max()
np.max(qq)

15

In [53]:
np.max(qq,axis=0) #4 th row

array([12, 13, 14, 15])

In [54]:
np.max(qq,axis=1) # 4th column

array([ 3,  7, 11, 15])

In [59]:
# min()

np.min(qq)

0

In [61]:
np.min(qq,axis=0) #minimun row is getting.

array([0, 1, 2, 3])

In [62]:
np.min(qq,axis=1) #min colmn is getting.

array([ 0,  4,  8, 12])

In [64]:
# mean() in 2_d Array.

print(np.mean(qq,axis=0)) 

print(np.mean(qq,axis=1))

[6. 7. 8. 9.]
[ 1.5  5.5  9.5 13.5]
