In [1]:
import numpy as np


In [2]:
# any
# all
# True / False

In [3]:
arr1 = np.array([11,22,33,44,0])
print(arr1)

[11 22 33 44  0]


In [4]:
# This method returns True if at least one element in the input array evaluates to True when a logical operation is applied element-wise. 
# It returns False if all elements are False.
np.any(arr1)

True

In [5]:
arr1 = np.array([0,0,0,0,0])
print(arr1)

[0 0 0 0 0]


In [6]:
np.any(arr1) # All the elememt is false.

False

In [7]:
arr1 = np.array([11,0,0,0,0])
print(arr1)

[11  0  0  0  0]


In [8]:
np.any(arr1)# atleast one element is true then its False.

True

In [9]:
# all():This method returns True if all elements in the input array evaluate to True when a logical operation is applied element-wise. 
# It returns False if at least one element is False.

arr2 = np.array([0,0,0,0,1])
print(arr2)

[0 0 0 0 1]


In [10]:
np.all(arr2) # Because 4-elements is False, ans is false.

False

In [12]:
arr3 = np.array([0,1,1,1,1])
print(arr3)

[0 1 1 1 1]


In [13]:
arr3

array([0, 1, 1, 1, 1])

In [14]:
np.all(arr3) # atlest 1 elements is false,getting false.

False

In [15]:
arr4 = np.array([1,1,1,1,1])
print(arr4)

[1 1 1 1 1]


In [16]:
np.all(arr4)#Because all elements is true.

True

In [17]:
aa =np.array([44,55])
bb = np.array([1,2])

print(aa)
print(bb)

[44 55]
[1 2]


In [18]:
aa > bb

array([ True,  True])

In [19]:
# any()
np.any(aa > bb) # Both are true

True

In [20]:
np.any(aa < bb) # Both are False.

False

In [21]:
aa < bb

array([False, False])

In [22]:
# all()

np.all(aa > bb) # Both are True

True

In [23]:
np.all(aa  < bb ) #both are False

False

In [24]:
aa1 =np.array([44,55,66,77])
bb1 = np.array([1,2,3,99])


In [27]:
print(aa1)
print(bb1)

[44 55 66 77]
[ 1  2  3 99]


In [30]:
aa1 > bb1

array([ True,  True,  True, False])

In [28]:
# any
np.any(aa1 > bb1)

True

In [29]:
np.any(aa1 < bb1)

True

In [31]:
# all()

np.all(aa1 > bb1)

False

In [32]:
np.all(aa1 < bb1)

False

In [33]:
##################### Sorting   ###########################.

In [34]:
arr = np.array([34,31,56,78,99,23,67,9])
print(arr)

[34 31 56 78 99 23 67  9]


In [35]:
# sort():sorting the array elemetns ordered
np.sort(arr)

array([ 9, 23, 31, 34, 56, 67, 78, 99])

In [37]:
np.sort(arr)

array([ 9, 23, 31, 34, 56, 67, 78, 99])

In [39]:
# argsort()
np.argsort(arr)

array([7, 5, 1, 0, 2, 6, 3, 4], dtype=int64)

In [42]:
arrr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arrr)

[0 1 2 3 4 5 6 7 8 9]


In [44]:
print(np.argsort(arrr))

[0 1 2 3 4 5 6 7 8 9]


In [46]:
# Traditional ways in Py.
descending_ans = arr[::-1]
descending_ans

array([ 9, 67, 23, 99, 78, 56, 31, 34])

In [45]:
# Smart way in numPy.
np.flip(arr) # indexwise reversed

array([ 9, 67, 23, 99, 78, 56, 31, 34])