In [1]:
import numpy as np

In [ ]:
# Numpy support only homogeneous data type('otherwise converting data type')

In [ ]:
# Loading the raw data into numpy

In [9]:
# import data file from fileManager (file store should in the same folder otherwise give the file path)
# Convertig the All elements into "str"dataType
data = np.loadtxt('fitbit.txt',dtype='str')


In [7]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [8]:
print(data)

[['06-10-2017' '5464' '200' '181' '6' '0' '68']
 ['07-10-2017' '7167' '200' '208' '6' '0' '68']
 ['08-10-2017' '9874' '300' '341' '5' '0' '68']
 ['09-10-2017' '4969' '100' '190' '8' '0' '68']
 ['10-10-2017' '8538' '300' '307' '5' '0' '68']
 ['11-10-2017' '9875' '300' '302' '5' '0' '68']
 ['12-10-2017' '4662' '100' '198' '8' '0' '68']
 ['13-10-2017' '6310' '200' '201' '6' '0' '68']
 ['14-10-2017' '7556' '200' '195' '6' '0' '68']
 ['15-10-2017' '9073' '300' '327' '5' '0' '68']
 ['16-10-2017' '9690' '300' '331' '5' '0' '68']
 ['17-10-2017' '9146' '300' '318' '5' '0' '68']
 ['18-10-2017' '9752' '300' '344' '5' '0' '68']
 ['19-10-2017' '6974' '200' '204' '6' '0' '68']
 ['20-10-2017' '5619' '200' '180' '6' '0' '68']
 ['21-10-2017' '6889' '200' '201' '6' '0' '68']
 ['22-10-2017' '8616' '300' '329' '5' '0' '68']
 ['23-10-2017' '9131' '300' '315' '5' '0' '68']
 ['24-10-2017' '4211' '100' '197' '8' '0' '68']
 ['25-10-2017' '4291' '100' '184' '8' '0' '68']
 ['26-10-2017' '8569' '300' '328' '5' '0

In [10]:
# Checking the various parameter
'''1.size
2.shape
3.ndim
4.dtype
'''

'1.size\n2.shape\n3.ndim\n4.dtype'

In [11]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [13]:
np.size(data)

182

In [14]:
np.shape(data) #(26,7) (rows,column)

(26, 7)

In [16]:
np.ndim(data)

2

In [17]:
np.dtype(data)

TypeError: Cannot construct a dtype from an array

In [18]:
data.dtype

dtype('<U10')

In [20]:
############## Cheking the data ###############

In [21]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [22]:
print(data[0])

['06-10-2017' '5464' '200' '181' '6' '0' '68']


In [23]:
data[0][4]

'6'

In [24]:
########## Transposing the data ############

In [25]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [27]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [28]:
data.T[1]

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [30]:
# packing and unpacking the data  

date,step_count,mood,calories_burned,hours_of_sleep ,bool_of_active ,weight_kg = data.T

In [31]:
data.date

AttributeError: 'numpy.ndarray' object has no attribute 'date'

In [32]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [33]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [36]:
hours_of_sleep

array(['6', '6', '5', '8', '5', '5', '8', '6', '6', '5', '5', '5', '5',
       '6', '6', '6', '5', '5', '8', '8', '5', '5', '5', '8', '6', '6'],
      dtype='<U10')

In [37]:
step_count.dtype

dtype('<U10')

In [41]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [42]:
###############    converting various features into int dtype     ###############


step_count = np.array(step_count,dtype='int')
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [44]:
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [45]:
date = np.array(date,dtype='int') #different data types
date

ValueError: invalid literal for int() with base 10: '06-10-2017'

In [46]:
weight_kg = np.array(weight_kg,dtype='int')

In [47]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [48]:
mood = np.array(mood,dtype='int')

In [49]:
mood

array([200, 200, 300, 100, 300, 300, 100, 200, 200, 300, 300, 300, 300,
       200, 200, 200, 300, 300, 100, 100, 300, 300, 300, 100, 200, 200])