In [1]:
import numpy as np

In [2]:
# numpy support only homogenous data type

In [3]:
# Loading the raw data into numpy
data = np.loadtxt('fitbit.txt',dtype='str') #converintg all the elements into string data type

In [4]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [5]:
print(data)

[['06-10-2017' '5464' '200' '181' '6' '0' '68']
 ['07-10-2017' '7167' '200' '208' '6' '0' '68']
 ['08-10-2017' '9874' '300' '341' '5' '0' '68']
 ['09-10-2017' '4969' '100' '190' '8' '0' '68']
 ['10-10-2017' '8538' '300' '307' '5' '0' '68']
 ['11-10-2017' '9875' '300' '302' '5' '0' '68']
 ['12-10-2017' '4662' '100' '198' '8' '0' '68']
 ['13-10-2017' '6310' '200' '201' '6' '0' '68']
 ['14-10-2017' '7556' '200' '195' '6' '0' '68']
 ['15-10-2017' '9073' '300' '327' '5' '0' '68']
 ['16-10-2017' '9690' '300' '331' '5' '0' '68']
 ['17-10-2017' '9146' '300' '318' '5' '0' '68']
 ['18-10-2017' '9752' '300' '344' '5' '0' '68']
 ['19-10-2017' '6974' '200' '204' '6' '0' '68']
 ['20-10-2017' '5619' '200' '180' '6' '0' '68']
 ['21-10-2017' '6889' '200' '201' '6' '0' '68']
 ['22-10-2017' '8616' '300' '329' '5' '0' '68']
 ['23-10-2017' '9131' '300' '315' '5' '0' '68']
 ['24-10-2017' '4211' '100' '197' '8' '0' '68']
 ['25-10-2017' '4291' '100' '184' '8' '0' '68']
 ['26-10-2017' '8569' '300' '328' '5' '0

In [7]:
# Transposing the data
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [8]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [10]:
data.T[1]

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [13]:
# packing and unpacking the data
date, step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T

In [14]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [15]:
hours_of_sleep

array(['6', '6', '5', '8', '5', '5', '8', '6', '6', '5', '5', '5', '5',
       '6', '6', '6', '5', '5', '8', '8', '5', '5', '5', '8', '6', '6'],
      dtype='<U10')

In [16]:
weight_kg

array(['68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68'], dtype='<U10')

In [17]:
# converting various features into int dtype

In [26]:
#mood = np.array(mood,dtype='int')

In [28]:
#mood

In [46]:
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')
step_count = np.array(step_count,dtype='int')

print(calories_burned)
print(hours_of_sleep)
print(step_count)

[181 208 341 190 307 302 198 201 195 327 331 318 344 204 180 201 329 315
 197 184 328 322 327 148 235 184]
[6 6 5 8 5 5 8 6 6 5 5 5 5 6 6 6 5 5 8 8 5 5 5 8 6 6]
[5464 7167 9874 4969 8538 9875 4662 6310 7556 9073 9690 9146 9752 6974
 5619 6889 8616 9131 4211 4291 8569 9337 8475 4510 6347 5911]


In [ ]:
# taking a closer look inside the mood column

In [21]:
mood.ndim

1

In [22]:
# To get the Number of Unique Values?

np.unique(mood)

array([100, 200, 300])

In [23]:
'''
100 -> Sad
200 -> Neutral
300 -> happy
'''

'\n100 Sad\n200 Neutral\n300 happy\n'

In [24]:
# converting the numerical form to string format

In [32]:
mood = np.array(mood,dtype='str')

In [33]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U11')

In [34]:
mood == '100'#using this as mask

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [37]:
mood[mood =='100'] ='Sad'

In [38]:
mood

array(['200', '200', '300', 'Sad', '300', '300', 'Sad', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       'Sad', 'Sad', '300', '300', '300', 'Sad', '200', '200'],
      dtype='<U11')

In [39]:
mood[mood =='200'] ='Neutral'

In [40]:
mood

array(['Neutral', 'Neutral', '300', 'Sad', '300', '300', 'Sad', 'Neutral',
       'Neutral', '300', '300', '300', '300', 'Neutral', 'Neutral',
       'Neutral', '300', '300', 'Sad', 'Sad', '300', '300', '300', 'Sad',
       'Neutral', 'Neutral'], dtype='<U11')

In [41]:
mood[mood =='300'] ='Happy'

In [42]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U11')

In [43]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U11')

In [44]:
############# working on step count   ####################

In [47]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [48]:
np.max(step_count)

9875

In [49]:
np.min(step_count)

4211

In [50]:
np.mean(step_count)

7344.461538461538

In [51]:
np.argmax(step_count) # the index position of the max val

5

In [ ]:
# calling the data from dates corrousponding to same index position

In [52]:
date[5]

'11-10-2017'

In [54]:
date[np.argmax(step_count)]

'11-10-2017'

In [58]:
date[np.argmin(step_count)]

'24-10-2017'

In [59]:
date[np.max(step_count)]

IndexError: index 9875 is out of bounds for axis 0 with size 26

In [60]:
date[np.min(step_count)]

IndexError: index 4211 is out of bounds for axis 0 with size 26

In [61]:
################## Frequency of Mood ####################

In [62]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U11')

In [64]:
# checking the 'count' of each mood type

len(mood[mood == '100']= 'Sad')

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (1297393008.py, line 3)

In [65]:
len(mood[mood == 'Sad'])# 5

5

In [66]:
len(mood[mood == 'Neutral'])#9

9

In [67]:
len(mood[mood == 'Happy'])#12

12

In [70]:
np.unique(mood,return_counts=True) #return_counts=True is the second parameter of the unique method.

(array(['Happy', 'Neutral', 'Sad'], dtype='<U11'),
 array([12,  9,  5], dtype=int64))

In [71]:
step_count[mood == 'Sad']

array([4969, 4662, 4211, 4291, 4510])

In [72]:
step_count[mood == 'Neutral']

array([5464, 7167, 6310, 7556, 6974, 5619, 6889, 6347, 5911])

In [73]:
step_count[mood == 'Happy']

array([9874, 8538, 9875, 9073, 9690, 9146, 9752, 8616, 9131, 8569, 9337,
       8475])

In [74]:
# Calculate Mean count when mood is 'Sad'

np.mean(step_count[mood == 'Sad'])

4528.6

In [75]:
# Calculate Mean count when mood is 'Neutral'

np.mean(step_count[mood == 'Neutral'])

6470.777777777777

In [76]:
# Calculate Mean count when mood is 'Happy'

np.mean(step_count[mood == 'Happy'])

9173.0

In [77]:
# Calculate Mean count when mood is 'Sad'

np.average(step_count[mood == 'Sad'])

4528.6

In [78]:
# Calculate Mean count when mood is 'Neutral'

np.average(step_count[mood == 'Neutral']) # avrege and mean is the same method.

6470.777777777777